In [10]:
#建立LIST
a = [1,3,5,7,9]
a*2
b=[2,4,6,8,10]
a+b
result = []
for i in range(5):
    result.append(a[i]+b[i])
    
result

    

In [19]:
import numpy as np
#透過list建立ndArry->可以做陣列運算
a=[1,3,5,7,9]
b = [2,4,6,8,10]
a_array = np.array(a)
a_array*2

b_array =np.array(b)
a_array + b_array


array([ 3,  7, 11, 15, 19])

In [31]:
#使用python建立5個亂數的元素的list
import random
[random.randint(50,100) for _ in range(5)]




[85, 60, 64, 86, 95]

In [26]:
np.random.randint(50,high=100,size=5)


array([76, 85, 79, 84, 53])

In [27]:
import numpy as np
np.random.randint(50,high=100,size=(50,5))

array([[94, 51, 96, 50, 87],
       [95, 80, 51, 82, 99],
       [94, 87, 52, 97, 57],
       [69, 68, 62, 86, 53],
       [88, 73, 79, 96, 52],
       [87, 80, 88, 96, 91],
       [59, 57, 58, 55, 68],
       [70, 55, 98, 89, 76],
       [93, 94, 60, 64, 86],
       [54, 55, 64, 72, 81],
       [61, 80, 92, 85, 93],
       [83, 85, 51, 56, 62],
       [55, 84, 95, 76, 84],
       [87, 88, 71, 70, 72],
       [89, 70, 70, 75, 98],
       [71, 78, 91, 91, 82],
       [75, 69, 65, 52, 98],
       [96, 57, 79, 60, 76],
       [58, 59, 80, 92, 92],
       [99, 71, 83, 50, 99],
       [72, 96, 64, 86, 93],
       [74, 61, 71, 90, 72],
       [66, 65, 88, 95, 80],
       [82, 63, 58, 51, 57],
       [95, 74, 68, 99, 70],
       [57, 77, 56, 72, 59],
       [84, 69, 83, 66, 64],
       [87, 85, 98, 66, 99],
       [92, 94, 63, 87, 88],
       [98, 82, 93, 60, 86],
       [82, 87, 80, 94, 59],
       [91, 58, 68, 99, 77],
       [96, 99, 85, 92, 50],
       [54, 83, 94, 77, 70],
       [84, 78